//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vertical_lift.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class finger_id
    {
        public int MTransNo { get; set; }
        public short finger { get; set; }
        public string status { get; set; }
    }
}
