//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vertical_lift.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods_Existing
    {
        public int MTransNo { get; set; }
        public int Side { get; set; }
        public int TrayNo { get; set; }
        public string BinType { get; set; }
        public string Dimension { get; set; }
        public int Location { get; set; }
        public Nullable<int> BinLocation { get; set; }
        public Nullable<int> BinBarcode { get; set; }
        public string QualityInspection { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> MaxQty { get; set; }
    }
}
