//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vertical_lift.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plc_tags
    {
        public int MTransNo { get; set; }
        public string PLCIPAddre { get; set; }
        public string Tags { get; set; }
        public string DataBit { get; set; }
        public string TagData { get; set; }
        public string TagAction { get; set; }
        public string ErrorDescription { get; set; }
        public string PLCOperation { get; set; }
        public string Desription { get; set; }
        public string Status { get; set; }
        public string TagType { get; set; }
    }
}
