//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vertical_lift.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refill_Temp_Table1
    {
        public int MTransNo { get; set; }
        public int BinNo { get; set; }
        public int Side { get; set; }
        public int TrayNo { get; set; }
        public int BinBarcode { get; set; }
        public string GRNNO { get; set; }
        public string MaterialDesc { get; set; }
        public int MaterialBarcode { get; set; }
        public string BatchNo { get; set; }
        public string Style { get; set; }
        public int Qty { get; set; }
        public string Status { get; set; }
    }
}
