//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vertical_lift.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refill_Temp_Table
    {
        public int MTransNo { get; set; }
        public Nullable<int> BinNo { get; set; }
        public Nullable<int> Side { get; set; }
        public Nullable<int> TrayNo { get; set; }
        public string BinType { get; set; }
        public Nullable<int> BinBarcode { get; set; }
        public string GRNNO { get; set; }
        public string MaterialDesc { get; set; }
        public Nullable<int> MaterialBarcode { get; set; }
        public string BatchNo { get; set; }
        public string Style { get; set; }
        public Nullable<int> RefilQty { get; set; }
        public Nullable<int> AvlQty { get; set; }
        public string Status { get; set; }
    }
}
