//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vertical_lift.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class S1542Entities : DbContext
    {
        public S1542Entities()
            : base("name=S1542Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BinMaster> BinMasters { get; set; }
        public virtual DbSet<BinMasterTable> BinMasterTables { get; set; }
        public virtual DbSet<ExistingDetail> ExistingDetails { get; set; }
        public virtual DbSet<finger_id> finger_id { get; set; }
        public virtual DbSet<Goods_Existing> Goods_Existing { get; set; }
        public virtual DbSet<Load_Temp_Table> Load_Temp_Table { get; set; }
        public virtual DbSet<MaterialMaster> MaterialMasters { get; set; }
        public virtual DbSet<Refill_Temp_Table> Refill_Temp_Table { get; set; }
        public virtual DbSet<Refill_Temp_Table1> Refill_Temp_Table1 { get; set; }
        public virtual DbSet<TransactionDetail> TransactionDetails { get; set; }
        public virtual DbSet<TrayMaster> TrayMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
    }
}
